In [117]:
import pandas as pd

In [118]:
Tenure_2011 = pd.read_csv("../Dataset/Census 2011/Tenure 2011.csv", skiprows=8)
Occupation_2011 = pd.read_csv("../Dataset/Census 2011/Occupation 2011.csv", skiprows=9)
Ethnic_group_2011 = pd.read_csv("../Dataset/Census 2011/Ethnic group 2011.csv", skiprows=8)
Age_structure_2011 = pd.read_csv("../Dataset/Census 2011/Age structure 2011.csv", skiprows=8)

C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\2073926531.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  Ethnic_group_2011 = pd.read_csv("../Dataset/Census 2011/Ethnic group 2011.csv", skiprows=8)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\2073926531.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  Age_structure_2011 = pd.read_csv("../Dataset/Census 2011/Age structure 2011.csv", skiprows=8)

In [119]:
datadict_2011 = {
    'Tenure_2011': Tenure_2011,
    'Occupation_2011': Occupation_2011,
    'Ethnic_group_2011': Ethnic_group_2011,
    'Age_structure_2011': Age_structure_2011
}

In [120]:
Tenure_2021 = pd.read_csv("../Dataset/Census 2021/Tenure 2021.csv", skiprows=7)
Occupation_2021 = pd.read_csv("../Dataset/Census 2021/Occupation 2021.csv", skiprows=7)
Ethnic_group_2021 = pd.read_csv("../Dataset/Census 2021/Ethnic group 2021.csv", skiprows=7)
Age_structure_2021 = pd.read_csv("../Dataset/Census 2021/Age structure 2021.csv", skiprows=5)

C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\2503830196.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  Tenure_2021 = pd.read_csv("../Dataset/Census 2021/Tenure 2021.csv", skiprows=7)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\2503830196.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  Ethnic_group_2021 = pd.read_csv("../Dataset/Census 2021/Ethnic group 2021.csv", skiprows=7)

In [121]:
datadict_2021 = {
    'Tenure_2021': Tenure_2021,
    'Occupation_2021': Occupation_2021,
    'Ethnic_group_2021': Ethnic_group_2021,
    'Age_structure_2021': Age_structure_2021
}

In [122]:
LSOA11CD = pd.read_csv("../Output/LSOA11CD.csv")
LSOA21CD = pd.read_csv("../Output/LSOA21CD.csv")

In [123]:
Tenure_2011

,2011 super output area - lower layer,All households,Owned,Owned: Owned outright,Owned: Owned with a mortgage or loan,Shared ownership (part owned and part rented),Social rented,Social rented: Rented from council (Local Authority),Social rented: Other,Private rented,Private rented: Private landlord or letting agency,Private rented: Other,Living rent free
0,E01000001 : City of London 001A,876,533.0,355.0,178.0,3.0,41.0,33.0,8.0,264.0,247.0,17.0,35.0
1,E01000002 : City of London 001B,830,527.0,314.0,213.0,8.0,48.0,44.0,4.0,219.0,206.0,13.0,28.0
2,E01000003 : City of London 001C,817,327.0,184.0,143.0,1.0,295.0,239.0,56.0,177.0,166.0,11.0,17.0
3,E01000005 : City of London 001E,467,46.0,24.0,22.0,0.0,312.0,133.0,179.0,101.0,92.0,9.0,8.0
4,E01000006 : Barking and Dagenham 016A,543,345.0,136.0,209.0,0.0,18.0,11.0,7.0,178.0,163.0,15.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34752,W01001958 : Swansea 025H,836,259.0,112.0,147.0,3.0,235.0,51.0,184.0,330.0,308.0,22.0,9.0
34753,NaN,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34754,NaN,have been swapped between different geographic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34755,NaN,"be affected, particularly small counts at the ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
Tenure_2021

,2021 super output area - lower layer,Total: All households,Owned,Owned: Owns outright,Owned: Owns with a mortgage or loan,Shared ownership,Shared ownership: Shared ownership,Social rented,Social rented: Rents from council or Local Authority,Social rented: Other social rented,Private rented,Private rented: Private landlord or letting agency,Private rented: Other private rented,Lives rent free,Owns with a mortgage or loan or shared ownership,Private rented or lives rent free
0,E01011954 : Hartlepool 001A,963,535.0,246.0,289.0,2.0,2.0,262.0,140.0,122.0,164.0,146.0,18.0,0.0,291.0,164.0
1,E01011969 : Hartlepool 001B,601,508.0,333.0,175.0,0.0,0.0,22.0,7.0,15.0,71.0,61.0,10.0,0.0,175.0,71.0
2,E01011970 : Hartlepool 001C,485,438.0,271.0,167.0,1.0,1.0,6.0,3.0,3.0,40.0,33.0,7.0,0.0,168.0,40.0
3,E01011971 : Hartlepool 001D,521,456.0,190.0,266.0,4.0,4.0,10.0,3.0,7.0,51.0,41.0,10.0,0.0,270.0,51.0
4,E01033465 : Hartlepool 001F,739,583.0,207.0,376.0,0.0,0.0,33.0,14.0,19.0,123.0,106.0,17.0,0.0,376.0,123.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35672,NaN,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35673,NaN,have been swapped between different geographic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35674,NaN,by small amounts. Small counts at the lowest g...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35675,NaN,affected.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
# Loop over each dataset to perform cleaning operations
for name, df in datadict_2011.items():
    # Remove rows where the LSOA field is missing
    df.dropna(subset=['2011 super output area - lower layer'], inplace=True)

    # Split the column into LSOA code and Borough name
    df[['LSOA11CD', 'Borough']] = df['2011 super output area - lower layer'].str.split(' : ', expand=True)

    # Extract only the alphabetic part of the Borough name
    df['Borough'] = df['Borough'].str.extract(r'([A-Za-z\s]+)')

    # Filter rows to keep only those with valid LSOA codes
    df = df[df['LSOA11CD'].isin(LSOA11CD['LSOA11CD'])]

    # Drop the original raw column
    df.drop(columns=['2011 super output area - lower layer'], inplace=True)

    # Exyract the column names
    cols = df.columns.tolist()

    # Reorder: move last two columns to the front
    new_order = cols[-2:] + cols[:-2]
    df = df[new_order]

    # Update the cleaned DataFrame in the dictionary
    datadict_2011[name] = df

# Reassign the cleaned DataFrames back to their original variable names
Tenure_2011 = datadict_2011['Tenure_2011']
Occupation_2011 = datadict_2011['Occupation_2011']
Ethnic_group_2011 = datadict_2011['Ethnic_group_2011']
Age_structure_2011 = datadict_2011['Age_structure_2011']

C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3131086587.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2011 super output area - lower layer'], inplace=True)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3131086587.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2011 super output area - lower layer'], inplace=True)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3131086587.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2011 super output area - lower layer'], inplace=True)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3131086587.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2011 super output area - lower layer'], inplace=True)

In [126]:
# Loop over each dataset to perform cleaning operations
for name, df in datadict_2021.items():
    # Remove rows where the LSOA field is missing
    df.dropna(subset=['2021 super output area - lower layer'], inplace=True)

    # Split the column into LSOA code and Borough name
    df[['LSOA21CD', 'Borough']] = df['2021 super output area - lower layer'].str.split(' : ', expand=True)

    # Extract only the alphabetic part of the Borough name
    df['Borough'] = df['Borough'].str.extract(r'([A-Za-z\s]+)')

    # Filter rows to keep only those with valid LSOA codes
    df = df[df['LSOA21CD'].isin(LSOA21CD['LSOA21CD'])]

    # Drop the original raw column
    df.drop(columns=['2021 super output area - lower layer'], inplace=True)

    # Exyract the column names
    cols = df.columns.tolist()

    # Reorder: move last two columns to the front
    new_order = cols[-2:] + cols[:-2]
    df = df[new_order]
    
    # Update the cleaned DataFrame in the dictionary
    datadict_2021[name] = df

# Reassign the cleaned DataFrames back to their original variable names
Tenure_2021 = datadict_2021['Tenure_2021']
Occupation_2021 = datadict_2021['Occupation_2021']
Ethnic_group_2021 = datadict_2021['Ethnic_group_2021']
Age_structure_2021 = datadict_2021['Age_structure_2021']

C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3164881407.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2021 super output area - lower layer'], inplace=True)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3164881407.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2021 super output area - lower layer'], inplace=True)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3164881407.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2021 super output area - lower layer'], inplace=True)
C:\Users\wbwha\AppData\Local\Temp\ipykernel_24040\3164881407.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['2021 super output area - lower layer'], inplace=True)

In [129]:
# Define save path templates
save_path_2011 = "../Dataset/Census London 2011/{}.csv"
save_path_2021 = "../Dataset/Census London 2021/{}.csv"

# Save 2011 datasets
for name, df in datadict_2011.items():
    df.to_csv(save_path_2011.format(name), index=False)

# Save 2021 datasets
for name, df in datadict_2021.items():
    df.to_csv(save_path_2021.format(name), index=False)