In [26]:
import pandas as pd

In [27]:
df_num = pd.read_excel("../Dataset/Other Datasets/HPSSA Dataset 41 - Number of residential property sales by LSOA.xls", engine='xlrd', sheet_name='Data', skiprows=5)

In [28]:
# Select the data of year 2011 and 2021
df_num = df_num.iloc[:, :4].join(df_num.filter(regex="(2011|2021)$"))

In [29]:
# Select the data in London area
df_num = df_num[df_num['Local authority code'].str.startswith('E09')]

In [30]:
df_num

,Local authority code,Local authority name,LSOA code,LSOA name,Year ending Mar 2011,Year ending Jun 2011,Year ending Sep 2011,Year ending Dec 2011,Year ending Mar 2021,Year ending Jun 2021,Year ending Sep 2021,Year ending Dec 2021
28009,E09000001,City of London,E01000001,City of London 001A,34,33,38,36,21,32,35,35
28010,E09000001,City of London,E01000002,City of London 001B,74,60,45,54,24,38,42,40
28011,E09000001,City of London,E01000003,City of London 001C,41,41,46,40,16,28,27,24
28012,E09000001,City of London,E01000005,City of London 001E,5,9,12,15,1,2,3,4
28013,E09000001,City of London,E01032739,City of London 001F,45,60,70,75,18,23,25,41
...,...,...,...,...,...,...,...,...,...,...,...,...
32839,E09000033,Westminster,E01033604,Westminster 009J,2,1,0,2,2,3,2,2
32840,E09000033,Westminster,E01033605,Westminster 009K,15,15,11,7,1,4,5,8
32841,E09000033,Westminster,E01033606,Westminster 014F,23,19,21,25,8,19,17,18
32842,E09000033,Westminster,E01033607,Westminster 014G,21,22,24,23,14,20,17,18
32843,E09000033,Westminster,E01033608,Westminster 007G,50,54,46,42,13,22,18,21

In [31]:
df_num.columns

Index(['Local authority code', 'Local authority name', 'LSOA code',
       'LSOA name', 'Year ending Mar 2011', 'Year ending Jun 2011',
       'Year ending Sep 2011', 'Year ending Dec 2011', 'Year ending Mar 2021',
       'Year ending Jun 2021', 'Year ending Sep 2021', 'Year ending Dec 2021'],
      dtype='object')

In [32]:
columns_to_check = ['Year ending Mar 2011', 'Year ending Jun 2011',
       'Year ending Sep 2011', 'Year ending Dec 2011', 'Year ending Mar 2021',
       'Year ending Jun 2021', 'Year ending Sep 2021', 'Year ending Dec 2021']

counts = df_num[columns_to_check].apply(lambda col: (col == 0).sum())

print(counts)

Year ending Mar 2011     9
Year ending Jun 2011     9
Year ending Sep 2011    10
Year ending Dec 2011    12
Year ending Mar 2021    29
Year ending Jun 2021    16
Year ending Sep 2021    11
Year ending Dec 2021    10
dtype: int64

In [33]:
df_num['Number of sales 2011'] = df_num[['Year ending Mar 2011', 'Year ending Jun 2011', 'Year ending Sep 2011', 'Year ending Dec 2011']].sum(axis=1)
df_num.drop(columns=['Year ending Mar 2011', 'Year ending Jun 2011', 'Year ending Sep 2011', 'Year ending Dec 2011'], inplace=True)

df_num['Number of sales 2021'] = df_num[['Year ending Mar 2021', 'Year ending Jun 2021', 'Year ending Sep 2021', 'Year ending Dec 2021']].sum(axis=1)
df_num.drop(columns=['Year ending Mar 2021', 'Year ending Jun 2021', 'Year ending Sep 2021', 'Year ending Dec 2021'], inplace=True)

In [34]:
df_num.rename(columns={'LSOA code': 'LSOA11CD'}, inplace=True)

In [35]:
# Save file
df_num.to_csv("../Dataset/Other Datasets/Number of sales.csv", index=False)

In [36]:
# List of London borough names
london_boroughs = [
    "Barking and Dagenham", "Barnet", "Bexley", "Brent", "Bromley",
    "Camden", "City of London", "Croydon", "Ealing", "Enfield", "Greenwich",
    "Hackney", "Hammersmith and Fulham", "Haringey", "Harrow", "Havering",
    "Hillingdon", "Hounslow", "Islington", "Kensington and Chelsea", "Kingston upon Thames",
    "Lambeth", "Lewisham", "Merton", "Newham", "Redbridge",
    "Richmond upon Thames", "Southwark", "Sutton", "Tower Hamlets", "Waltham Forest",
    "Wandsworth", "Westminster"
    ]

In [37]:
df_pop_2011 = pd.read_csv("../Dataset/Other Datasets/census_population_2011.csv", skiprows=8)

In [38]:
import re

# Create a regular expression by joining all London boroughs, which will be used for matching
regex = r'\b(?:' + '|'.join(re.escape(b) for b in london_boroughs) + r')\b'

# Filter rows where the 'area_info' column contains any of the London boroughs
df_pop_london_2011 = df_pop_2011[df_pop_2011['2011 super output area - lower layer'].str.contains(regex, case=False, na=False, regex=True)]

# Extract LSOA code, assuming it's the part after the colon ':'
df_pop_london_2011['2011 super output area - lower layer'] = df_pop_london_2011['2011 super output area - lower layer'].str.split(':').str[0].str.strip()

df_pop_london_2011.rename(columns={'2011 super output area - lower layer': 'LSOA11CD'}, inplace=True)

# Display the resulting dataframe
df_pop_london_2011 = df_pop_london_2011.iloc[:,:2]

df_pop_london_2011.rename(columns={'All usual residents':'All residents'}, inplace=True)

C:\Users\wbwha\AppData\Local\Temp\ipykernel_2040\1074051436.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop_london_2011['2011 super output area - lower layer'] = df_pop_london_2011['2011 super output area - lower layer'].str.split(':').str[0].str.strip()
C:\Users\wbwha\AppData\Local\Temp\ipykernel_2040\1074051436.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop_london_2011.rename(columns={'2011 super output area - lower layer': 'LSOA11CD'}, inplace=True)

In [39]:
df_pop_london_2011

        LSOA11CD All residents
0      E01000001          1465
1      E01000002          1436
2      E01000003          1346
3      E01000005           985
4      E01000006          1703
...          ...           ...
32817  E01033742          1352
32818  E01033743          2038
32819  E01033744          1845
32820  E01033745          1820
32821  E01033746          1464

[4835 rows x 2 columns]

In [40]:
# Save file
df_pop_london_2011.to_csv("../Output/Population_2011.csv", index=False)

In [41]:
df_pop_2001 = pd.read_csv("../Dataset/Other Datasets/census_population_2001.csv", skiprows=7)

In [42]:
# Create a regular expression by joining all London boroughs, which will be used for matching
regex = r'\b(?:' + '|'.join(re.escape(b) for b in london_boroughs) + r')\b'

# Filter rows where the 'area_info' column contains any of the London boroughs
df_pop_london_2001 = df_pop_2001[df_pop_2001['2001 super output areas - lower layer'].str.contains(regex, case=False, na=False, regex=True)]

# Extract LSOA code, assuming it's the part after the colon ':'
df_pop_london_2001['2001 super output areas - lower layer'] = df_pop_london_2001['2001 super output areas - lower layer'].str.split(':').str[0].str.strip()
 
df_pop_london_2001.rename(columns={'2001 super output areas - lower layer': 'LSOA01CD'}, inplace=True)

# Display the resulting dataframe
df_pop_london_2001 = df_pop_london_2001.iloc[:,:2]

C:\Users\wbwha\AppData\Local\Temp\ipykernel_2040\2863941853.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop_london_2001['2001 super output areas - lower layer'] = df_pop_london_2001['2001 super output areas - lower layer'].str.split(':').str[0].str.strip()
C:\Users\wbwha\AppData\Local\Temp\ipykernel_2040\2863941853.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop_london_2001.rename(columns={'2001 super output areas - lower layer': 'LSOA01CD'}, inplace=True)

In [43]:
df_pop_london_2001

       LSOA01CD All people
0     E01000001       1600
1     E01000002       1470
2     E01000003       1537
3     E01000004       1505
4     E01000005       1073
...         ...        ...
4760  E01004761       1439
4761  E01004762       1470
4762  E01004763       1541
4763  E01004764       1482
4764  E01004765       1531

[4765 rows x 2 columns]

In [44]:
# Save file
df_pop_london_2001.to_csv("../Output/Population_2001.csv", index=False)

In [45]:
df_imd_2019 = pd.read_excel("../Dataset/IMD/IMD_2019.xlsx", sheet_name='IoD2019 Scores')

In [46]:
# Select the data from London area
df_imd_london_2019 = df_imd_2019[df_imd_2019['Local Authority District code (2019)'].str.startswith('E09')]
# Rename the column of LSOA code for data mapping
df_imd_london_2019.rename(columns={'LSOA code (2011)':'LSOA11CD'}, inplace=True)

C:\Users\wbwha\AppData\Local\Temp\ipykernel_2040\3204636501.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_imd_london_2019.rename(columns={'LSOA code (2011)':'LSOA11CD'}, inplace=True)

In [47]:
df_imd_london_2019.to_csv("../Dataset/IMD/IMD_london_2019.csv", index=False)

In [48]:
df_imd_2010 = pd.read_excel("../Dataset/IMD/IMD_2010.xls", sheet_name='IMD 2010')

In [49]:
# Select the data from London area
df_imd_london_2010 = df_imd_2010[df_imd_2010['GOR NAME'] == 'London']
# Rename the column of LSOA code for data mapping
df_imd_london_2010.rename(columns={'LSOA CODE':'LSOA01CD'}, inplace=True)

C:\Users\wbwha\AppData\Local\Temp\ipykernel_2040\1989080430.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_imd_london_2010.rename(columns={'LSOA CODE':'LSOA01CD'}, inplace=True)

In [50]:
df_imd_london_2010.to_csv("../Dataset/IMD/IMD_london_2010.csv", index=False)