In [1]:
import random
import numpy as np

random.seed(42)
np.random.seed(42)

import pandas as pd

import matplotlib.pyplot as plt

In [2]:
import torch

In [3]:
lsoa_id = sorted(pd.read_csv("../Output/LSOA21CD.csv")["LSOA21CD"].tolist())

In [4]:
embeddings = np.load('../Model/emb_all-MiniLM-L6-v2.npy')

description_topic = pd.read_csv('../Output/NLP Output/feature_extraction_origin.csv')

In [5]:
sbert_df = pd.DataFrame(embeddings)

In [6]:
import ast

description_topic['prob_vector'] = description_topic['probabilities'].apply(ast.literal_eval)

In [7]:
topic_matrix = np.vstack(description_topic['prob_vector'].values)
topic_df = pd.DataFrame(topic_matrix, columns=[f'topic_{i}' for i in range(topic_matrix.shape[1])])

In [8]:
topic_df

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,...,topic_1164,topic_1165,topic_1166,topic_1167,topic_1168,topic_1169,topic_1170,topic_1171,topic_1172,topic_1173
0,2.446652e-04,2.102272e-04,1.856370e-04,1.605959e-04,2.068002e-04,9.624113e-05,8.893767e-05,1.276421e-04,8.727591e-05,1.263238e-04,...,1.995287e-04,7.861678e-05,2.754978e-04,8.513392e-05,5.468070e-04,3.630117e-04,2.755160e-04,9.461714e-05,3.208686e-04,8.526006e-05
1,3.113932e-04,3.376181e-04,3.395465e-04,4.959566e-04,2.979200e-04,6.141201e-04,2.503583e-03,2.650973e-04,5.355277e-04,6.679801e-04,...,3.043132e-04,2.008176e-03,2.909381e-04,7.436996e-04,2.925270e-04,3.422912e-04,3.230111e-04,5.757604e-04,3.112692e-04,8.765112e-04
2,2.018424e-306,2.240213e-306,2.140056e-306,9.606314e-307,1.152876e-306,6.933691e-307,5.744552e-307,6.489069e-307,5.799234e-307,8.472187e-307,...,1.135957e-306,4.863412e-307,1.140061e-306,5.769287e-307,1.698033e-306,3.274382e-306,4.219617e-306,6.797494e-307,3.279195e-306,5.597241e-307
3,2.227479e-01,1.119299e-03,9.470741e-04,5.334149e-04,9.124164e-04,3.766496e-04,3.579308e-04,4.531367e-04,3.224771e-04,4.968690e-04,...,8.658896e-04,3.044985e-04,9.751549e-04,3.697357e-04,1.135450e-03,1.199348e-03,9.836974e-04,3.682604e-04,1.171770e-03,3.398987e-04
4,3.546263e-04,3.606364e-04,3.005669e-04,1.606891e-04,3.023880e-04,1.098932e-04,9.685141e-05,1.338884e-04,9.956400e-05,1.330105e-04,...,2.816085e-04,8.563934e-05,3.801685e-04,9.591384e-05,1.622464e-03,6.037977e-04,5.651797e-04,1.089447e-04,7.078036e-04,9.438917e-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113933,1.225738e-306,9.051317e-307,1.095371e-306,9.655573e-307,7.627033e-306,5.866553e-307,4.920145e-307,9.023499e-307,5.019203e-307,7.632633e-307,...,4.197128e-306,4.364312e-307,3.411543e-306,5.789262e-307,9.623761e-307,1.010208e-306,8.960118e-307,5.739163e-307,9.757870e-307,5.394807e-307
113934,9.973086e-05,1.053339e-04,1.090802e-04,9.915776e-05,1.100874e-04,8.110994e-05,7.927814e-05,1.978663e-04,7.627252e-05,9.525827e-05,...,1.157535e-04,7.628379e-05,1.057151e-04,7.953353e-05,9.840842e-05,9.933408e-05,1.002743e-04,8.015023e-05,1.029122e-04,8.161100e-05
113935,1.196073e-03,1.633515e-03,1.360441e-01,7.625211e-04,1.007015e-03,5.737693e-04,4.782645e-04,6.190871e-04,4.486433e-04,7.695608e-04,...,1.088201e-03,3.973232e-04,8.097842e-04,5.232795e-04,7.800821e-04,1.134304e-03,1.194308e-03,5.550437e-04,1.181261e-03,4.880027e-04
113936,2.030840e-04,2.164380e-04,2.427999e-04,9.816334e-04,2.267625e-04,1.281264e-03,4.618953e-04,1.785887e-04,8.077845e-04,5.440602e-04,...,2.306065e-04,4.190385e-04,2.164311e-04,5.100579e-04,1.977962e-04,2.420113e-04,2.264404e-04,1.129502e-03,2.137789e-04,7.165740e-04
113937,4.518960e-307,4.942539e-307,4.958596e-307,8.013670e-307,4.438509e-307,8.976229e-307,2.736666e-306,4.134430e-307,8.618440e-307,1.010372e-306,...,4.546465e-307,1.928598e-305,4.379900e-307,8.728263e-307,4.424429e-307,5.127055e-307,4.827057e-307,8.473713e-307,4.656080e-307,1.200031e-306

In [9]:
sbert_df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.076016,0.034962,0.008830,-0.030271,0.029285,0.020089,-0.035852,-0.001645,-0.142697,0.033583,...,0.065126,0.006564,0.044565,-0.049141,0.077937,0.043583,-0.106447,0.013555,-0.028803,0.000986
1,0.012683,0.056926,0.062753,-0.033011,-0.081705,-0.070398,-0.088762,-0.074114,-0.083479,0.054334,...,0.082411,0.065045,0.019736,0.052101,0.014027,0.023311,0.080643,-0.023715,0.038558,0.048565
2,0.108826,-0.008235,0.006579,-0.012608,-0.096108,-0.024566,-0.091676,0.049880,-0.094864,0.029676,...,0.014257,0.066394,-0.035941,0.029888,0.066311,0.028401,-0.005959,-0.010439,0.014559,-0.005935
3,0.048895,-0.000744,0.030964,-0.015419,-0.027435,0.096007,-0.033008,-0.002480,-0.024027,0.017367,...,0.031683,-0.035986,-0.031902,-0.043661,0.033311,0.045294,-0.027301,-0.041521,0.019800,-0.013135
4,0.081007,-0.006195,-0.055365,-0.023709,-0.032170,0.038793,-0.092000,0.040551,-0.029253,-0.008712,...,0.037091,0.002158,-0.088090,-0.048079,0.015366,0.044858,-0.056914,-0.063085,0.002108,-0.064479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113933,-0.028061,0.026191,-0.000374,-0.012050,-0.027593,0.029289,-0.062703,0.020761,-0.040650,0.034601,...,0.058522,0.015918,-0.029230,-0.057205,0.039704,0.027925,-0.019981,-0.024097,-0.020959,0.033360
113934,0.021426,-0.012665,-0.009204,-0.003076,-0.043428,-0.009269,-0.018391,0.032135,-0.089859,-0.042652,...,-0.011409,0.051760,0.020795,0.031972,0.061616,0.037672,0.003229,-0.034606,0.068963,0.014466
113935,0.116497,0.070805,-0.010845,-0.045663,-0.043163,-0.021304,-0.041905,0.013408,-0.083206,0.075492,...,0.055119,0.048625,0.000119,0.002588,0.073450,0.006472,-0.023461,-0.054904,-0.022584,0.032515
113936,0.019259,-0.027185,-0.001134,-0.006919,-0.067833,0.008458,-0.072546,0.048859,-0.087006,-0.004796,...,0.038901,0.056045,0.031970,-0.052313,0.078986,0.006388,-0.002567,-0.048896,0.020874,0.036868
113937,0.070634,0.039464,0.055230,-0.033307,-0.077691,-0.056935,-0.055601,-0.031043,-0.041895,0.035791,...,0.085646,0.082182,-0.043427,0.010230,0.043616,0.044581,0.104624,0.005593,0.034285,-0.006220

In [10]:
from sklearn.preprocessing import StandardScaler

scaler_sbert = StandardScaler()
scaler_topic = StandardScaler()

sbert_scaled = scaler_sbert.fit_transform(sbert_df)
topic_scaled = scaler_topic.fit_transform(topic_df)

X_standard = np.hstack([sbert_scaled, topic_scaled])
feature_dim = X_standard.shape[1]

In [11]:
df_features = description_topic[['LSOA21CD', 'year']].copy()
df_features['vector'] = list(X_standard)

In [12]:
df_features_ = pd.concat([df_features, topic_df, sbert_df], axis=1)
df_features_.drop(columns=['vector'], inplace=True)

In [18]:
train_not_grouped_5class = df_features_[df_features_['year'].isin(range(2002, 2012))]
train_not_grouped_7class = df_features_[df_features_['year'].isin(range(2002, 2012))]

X_predict_not_grouped = df_features_[df_features_['year'].isin(range(2012, 2022))]

In [14]:
Y_5 = pd.read_csv("../Output/Gentrification label_2021_5class.csv").sort_values("LSOA21CD").reset_index(drop=True)

Y_7 = pd.read_csv("../Output/Gentrification label_2021_7class.csv").sort_values("LSOA21CD").reset_index(drop=True)

In [19]:
train_not_grouped_7class = pd.merge(train_not_grouped_7class, Y_7, on='LSOA21CD', how='left')
train_not_grouped_5class = pd.merge(train_not_grouped_5class, Y_5, on='LSOA21CD', how='left')

In [20]:
label_mapping_5 = {
    "Class 0 - Affluent and Middle Class": 0,
    "Class 1 - Stable Low-income": 1,
    "Class 2 - Ongoing Displacement": 2,
    "Class 3 - At Risk of Gentrification": 3,
    "Class 4 - Ongoing Gentrification": 4
}
train_not_grouped_5class["class_int"] = train_not_grouped_5class["gentrification_class"].map(label_mapping_5)

In [16]:
label_mapping_7 = {
    "Class 0 - Stable Affluent and Moderate-income": 0,
    "Class 1 - Upgrading or Gentrified": 1,
    "Class 2 - Stable Low-income": 2,
    "Class 3 - Economically Decline": 3,
    "Class 4 - Ongoing Displacement": 4,
    "Class 5 - At Risk of Gentrification": 5,
    "Class 6 - Ongoing Gentrification": 6
}
train_not_grouped_7class["class_int"] = train_not_grouped_7class["gentrification_class"].map(label_mapping_7)

In [21]:
train_not_grouped_5class.to_csv("../Output/Pred Input/train_not_grouped_5class.csv", index=False)
train_not_grouped_7class.to_csv("../Output/Pred Input/train_not_grouped_7class.csv", index=False)

X_predict_not_grouped.to_csv("../Output/Pred Input/X_predict_not_grouped.csv", index=False)

In [26]:
def conversion(df_):
     
    list_of_rows = df_.values.tolist()
    array = np.array(list_of_rows) 

    df = description_topic[['LSOA21CD', 'year']].copy()
    df['vector'] = list(array)
    return df

def group_by_lsoa(year_range, df_features):
    df_sub = df_features[df_features['year'].isin(year_range)]
    grouped = df_sub.groupby('LSOA21CD')['vector'].apply(
        lambda v: np.mean(np.stack(v), axis=0)
    )
    return grouped.sort_index()

def fill_missing(vecs, lsoa_list, dim):
    X = np.zeros((len(lsoa_list), dim))
    for i, lsoa in enumerate(lsoa_list):
        if lsoa in vecs:
            X[i] = vecs[lsoa]
    return X

In [27]:
X_standard

array([[ 0.89221555,  0.65585244,  0.28538004, ..., -0.06126561,
        -0.04123121, -0.05699108],
       [-0.61536992,  1.18830884,  1.66928613, ..., -0.011382  ,
        -0.04225199,  0.02623823],
       [ 1.67322409, -0.39132032,  0.22761244, ..., -0.07107525,
        -0.07535197, -0.06595932],
       ...,
       [ 1.85581326,  1.5247457 , -0.21956787, ..., -0.01352985,
         0.05026182, -0.0146278 ],
       [-0.45884705, -0.85070032,  0.02964709, ...,  0.04602844,
        -0.05261898,  0.00941492],
       [ 0.7641021 ,  0.76497895,  1.47620475, ..., -0.07107525,
        -0.07535197, -0.06595932]])

In [51]:
topic_df_10 = topic_df.iloc[:, :10]
topic_df_50 = topic_df.iloc[:, :50]
topic_df_100 = topic_df.iloc[:, :100]
topic_df_200 = topic_df.iloc[:, :200]
topic_df_200 = topic_df.iloc[:, :200]
topic_df_500 = topic_df.iloc[:, :500]

In [37]:
df_topic_50 = conversion(topic_df_50)

In [42]:
df_topic_100 = conversion(topic_df_100)

In [47]:
df_topic_200 = conversion(topic_df_200)

In [52]:
df_topic_500 = conversion(topic_df_500)

In [29]:
df_topic_10 = conversion(topic_df_10)
df_topic = conversion(topic_df)
df_sbert = conversion(sbert_df)

In [38]:
train_vecs_topic_50 = group_by_lsoa(range(2002, 2012), df_topic_50)

In [43]:
train_vecs_topic_100 = group_by_lsoa(range(2002, 2012), df_topic_100)

In [48]:
train_vecs_topic_200 = group_by_lsoa(range(2002, 2012), df_topic_200)

In [53]:
train_vecs_topic_500 = group_by_lsoa(range(2002, 2012), df_topic_500)

In [32]:
train_vecs_topic_10 = group_by_lsoa(range(2002, 2012), df_topic_10)
train_vecs_topic = group_by_lsoa(range(2002, 2012), df_topic)
train_vecs_sbert = group_by_lsoa(range(2002, 2012), df_sbert)

# train_vecs = group_by_lsoa(range(2002, 2012))
# predict_vecs = group_by_lsoa(range(2012, 2022))

In [39]:
X_train_topic_50 = fill_missing(train_vecs_topic_50, lsoa_id, dim=50)

In [44]:
X_train_topic_100 = fill_missing(train_vecs_topic_100, lsoa_id, dim=100)

In [49]:
X_train_topic_200 = fill_missing(train_vecs_topic_200, lsoa_id, dim=200)

In [54]:
X_train_topic_500 = fill_missing(train_vecs_topic_500, lsoa_id, dim=500)

In [34]:
X_train_topic_10 = fill_missing(train_vecs_topic_10, lsoa_id, dim=10)
X_train_topic = fill_missing(train_vecs_topic, lsoa_id, dim=1174)
X_train_sbert = fill_missing(train_vecs_sbert, lsoa_id, dim=384)

# X_train = fill_missing(train_vecs, lsoa_id, feature_dim)
# X_predict = fill_missing(predict_vecs, lsoa_id, feature_dim)

In [57]:
label_mapping_5 = {
    "Class 0 - Affluent and Middle Class": 0,
    "Class 1 - Stable Low-income": 1,
    "Class 2 - Ongoing Displacement": 2,
    "Class 3 - At Risk of Gentrification": 3,
    "Class 4 - Ongoing Gentrification": 4
}

Y_5["label_int"] = Y_5["gentrification_class"].map(label_mapping_5)

label_dict_5 = dict(zip(Y_5["LSOA21CD"], Y_5["label_int"]))

y_train_5 = torch.full((len(lsoa_id),), -1, dtype=torch.long)

for i, lsoa in enumerate(lsoa_id):
    if lsoa in label_dict_5:
        y_train_5[i] = label_dict_5[lsoa]

In [59]:
label_mapping_7 = {
    "Class 0 - Stable Affluent and Moderate-income": 0,
    "Class 1 - Upgrading or Gentrified": 1,
    "Class 2 - Stable Low-income": 2,
    "Class 3 - Economically Decline": 3,
    "Class 4 - Ongoing Displacement": 4,
    "Class 5 - At Risk of Gentrification": 5,
    "Class 6 - Ongoing Gentrification": 6
}

Y_7["label_int"] = Y_7["gentrification_class"].map(label_mapping_7)

label_dict_7 = dict(zip(Y_7["LSOA21CD"], Y_7["label_int"]))

y_train_7 = torch.full((len(lsoa_id),), -1, dtype=torch.long)

for i, lsoa in enumerate(lsoa_id):
    if lsoa in label_dict_7:
        y_train_7[i] = label_dict_7[lsoa]

In [35]:
torch.save(torch.tensor(X_train_topic_10, dtype=torch.float32), "../Output/Pred Input/X_train_topic_10.pt")

In [40]:
torch.save(torch.tensor(X_train_topic_50, dtype=torch.float32), "../Output/Pred Input/X_train_topic_50.pt")

In [45]:
torch.save(torch.tensor(X_train_topic_100, dtype=torch.float32), "../Output/Pred Input/X_train_topic_100.pt")

In [50]:
torch.save(torch.tensor(X_train_topic_200, dtype=torch.float32), "../Output/Pred Input/X_train_topic_200.pt")

In [55]:
torch.save(torch.tensor(X_train_topic_500, dtype=torch.float32), "../Output/Pred Input/X_train_topic_500.pt")

In [37]:
torch.save(torch.tensor(X_train_topic, dtype=torch.float32), "../Output/Pred Input/X_train_topic.pt")

In [42]:
torch.save(torch.tensor(X_train_sbert, dtype=torch.float32), "../Output/Pred Input/X_train_sbert.pt")

In [ ]:
torch.save(torch.tensor(X_train, dtype=torch.float32), "../Output/Pred Input/X_train.pt")
torch.save(torch.tensor(X_predict, dtype=torch.float32), "../Output/Pred Input/X_predict.pt")

In [60]:
torch.save(y_train_5, "../Output/Pred Input/y_train_5.pt")
torch.save(y_train_7, "../Output/Pred Input/y_train_7.pt")